### ISSUE TITLE
java.lang.NullPointerException when joining a Continuum Server

### ISSUE THREAD

**Issue by Padrone56** [p455w0rd/p455w0rds-Library#14]
I think this error is related to the Mojang error, with language files using no underscores. The issue has been [fixed ](https://github.com/MinecraftForge/MinecraftForge/pull/5105#issuecomment-413663474)on Mojang's side, but I get this error from this library according to my log.

`[00:08:45] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://gitlab.com/p455w0rd/patrons/raw/master/patrons.txt
[00:08:45] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
[00:08:45] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[00:08:45] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
[00:08:45] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
[00:08:45] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at java.security.AccessController.doPrivileged(Native Method)
[00:08:45] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[00:08:45] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)`

This happens when I try to join a Continuum Server.

**Comment by p455w0rd** [comment]
update p455w0rdslib ..this is just cuz continuum is using an outdated version...nothing to do with the mojang bug

**Comment by mr2013** [comment]
Version p455w0rdslib-1.12-2.0.32 still spits out errors when the URL cannot be fetched, though the URL has been changed to "http://hindsley.us/patrons.txt"

Additionally, the config option EnableContributorCosmetics is not being respected.

**Comment by p455w0rd** [comment]
thank you! I just got my PC back up and running today, I am switching to amazon cloud to hopefully finally fix this..i'll put out an update soon, the option is being respected, but you're not a contributor..the wings will still show for other players that have them..this only disables them for the contributor trying to disable them...maybe its an option I should add..maybe if one were to contribute? I have too many other mods to work on atm to be adding functionality all willy nilly, sorry

**Comment by p455w0rd** [comment]
should be fixed - https://minecraft.curseforge.com/projects/p455w0rds-library/files
