### ISSUE TITLE
p455w0rdslib crashes when requesting a textfile from github

### ISSUE THREAD

**Issue by repvik** [p455w0rd/p455w0rds-Library#16]
```
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://gitlab.com/p455w0rd/patrons/raw/master/patrons.txt
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at java.security.AccessController.doPrivileged(Native Method)
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[00:11:59] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at p455w0rdslib.util.ContributorUtils$DLThread.run(ContributorUtils.java:316)
```

Github shows:

```
429
Too many requests received.
Please try again later.
```

on the url.

**Comment by p455w0rd** [comment]
yeah..update...I've been using amazon for hosting that file for quite a while now...and it's GitLab, not GitHub
