### ISSUE TITLE
patrons.txt never works

### ISSUE THREAD

**Issue by ouroborus** [p455w0rd/p455w0rds-Library#20]
https://gitlab.com/p455w0rd/patrons/raw/master/patrons.txt almost always triggers an exception with HTTP code 429. Perhaps alternate hosting is in order? Or catch the exception.

```
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://gitlab.com/p455w0rd/patrons/raw/master/patrons.txt
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at p455w0rdslib.util.ContributorUtils$DLThread.run(ContributorUtils.java:316)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://gitlab.com/p455w0rd/patrons/raw/master/patrons.txt
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[17:41:44] [TheRealp455w0rd Contributors DL Thread/INFO] [STDERR]: [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: 	at p455w0rdslib.util.ContributorUtils$DLThread.run(ContributorUtils.java:316)
```

**Comment by ouroborus** [comment]
Similar to #15 but different issue.

**Comment by p455w0rd** [comment]
what MC version? I've been using amazon for months now...for 1.10.2 and 1.12.2

**Comment by ouroborus** [comment]
My bad. I guess that's what I get for waiting around so long to report it.
