### ISSUE TITLE
[1.12.2] Crashing client to desktop

### ISSUE THREAD

**Issue by MacAttack-UK** [p455w0rd/p455w0rds-Library#47]
Hi, I added the following to the 'Antimatter Chemistry' (v1.2.19) pack :

WirelessCraftingTerminal-1.12.2-3.12.93
and Dependancies :
AE2WTLib-1.12.2-1.0.30
p455w0rdslib-1.12.2-2.2.156

Since adding it I'm getting what seems to be random (not every time) client crashes to desktop. The server however does not crash and the client log indicates the problem is with p455w0rdslib or something related to it from what I can make out.

[crash-2019-08-14_02.27.14-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3499479/crash-2019-08-14_02.27.14-client.txt)

Edit: I should add that it mostly happens when returning to my base via the /home command but it also happens when returning via the RFTools teleporter.

**Comment by Gunner76th** [comment]
Try disabling the shaders function of p455w0rdslib and see if that works for the time being. The first few lines identifies a concurrent modification issue, followed directly by an issue with the shaders: 

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at p455w0rdslib.api.client.shader.LightHandler.update(LightHandler.java:150)
	at p455w0rdslib.asm.Hooks.enableColoredLighting(Hooks.java:26)
```
While this is not a fix, it should function as a work around until updates are complete on the updated  p455w0rdslib mod as well as /dank/null (should you use that mod or it be in the modpack). You can disable the shaders from within the game by hitting Esc and clicking on Mod Options.

**Comment by FoxMcloud5655** [comment]
I'll give this a try.  In the meantime, I've gotten the same thing, just when it started raining, it crashed.
```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at p455w0rdslib.api.client.shader.LightHandler.update(LightHandler.java:150)
    at p455w0rdslib.asm.Hooks.enableColoredLighting(Hooks.java:26)
    at net.minecraft.client.renderer.RenderGlobal.renderBlockLayer(RenderGlobal.java:1133)
    at net.minecraft.client.renderer.RenderGlobal.renderBlockLayer(RenderGlobal.java:1125)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1331)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
```

**Comment by p455w0rd** [comment]
thank you @FoxMcloud5655 this might make that part somewhat reproduceable at least..i'll look into it soon

**Comment by FoxMcloud5655** [comment]
Of course!  Happy to help.

**Comment by p455w0rd** [comment]
should be resolved since I removed shaders
