### ISSUE TITLE
ConcurrentModificationException Crash in LightHandler/Enable Colored lighting

### ISSUE THREAD

**Issue by LoRes-Gamer** [p455w0rd/p455w0rds-Library#52]
My modpack is  crashing intermittently with no consistent way to reproduce. I play about daily and the crash happens about twice a month. This is in single-player mode, always at the same location in the library, based on stack trace/exception info. It doesn't appear to crash Java as it returns to the Java launcher OK. Three sample crash reports attached, together with latest minecraft/Forge log.
Notes: 
1) I haven't yet tried disabling Colored lighting in configs (assuming that's even possible).
2) This is occurring mostly during gameplay and not at startup or when loading a save file. One occurrence immediately after loading a save, but the save loaded successfully on retry.

[latest.log](https://github.com/p455w0rd/p455w0rds-Library/files/3704784/latest.log)

Exception stack:
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at p455w0rdslib.api.client.shader.LightHandler.update(LightHandler.java:150)
	at p455w0rdslib.asm.Hooks.enableColoredLighting(Hooks.java:26)
	at net.minecraft.client.renderer.RenderGlobal.func_174982_a(RenderGlobal.java:1133)
	at net.minecraft.client.renderer.RenderGlobal.func_174977_a(RenderGlobal.java:1125)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1334)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2019-10-08_17.53.25-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3704741/crash-2019-10-08_17.53.25-client.txt)
[crash-2019-09-17_03.30.23-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3704742/crash-2019-09-17_03.30.23-client.txt)
[crash-2019-10-06_08.47.31-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3704743/crash-2019-10-06_08.47.31-client.txt)

**Comment by LoRes-Gamer** [comment]
Above exception is confirmed to be using the default config file.  I will play with the settings a bit (apart from disabling colored lights completely) and see if it reduces the crash rate. Game is crashing more frequently now, 3rd time this week.

**Comment by DarkEyeDragon** [comment]
Same issue.

Seems to occur when moving around fast or when doing heavy chunk loading
[crash-2019-10-17_20.07.00-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3740699/crash-2019-10-17_20.07.00-client.txt)

**Comment by Ravalli03** [comment]
Getting same crash. 

https://pastebin.com/6G3PsxwM

I haven't had any issues the last few weeks playing, but today it has crashed twice. I set "colored light shader options" to false, I'll let you know if it stops the crashes.

**Comment by hiddenkrypt** [comment]
Same crash for me as well 

https://pastebin.com/UYS1jxGD

This is on a multiplayer server. At this point, any attempt to log in results in a crash. 

I set `B:EnableShaders=false` in _p455w0rdsLib.cfg_ and that seems to have stopped the crashes for me, so if you don't mind turning the system off entirely there's at least a workaround

**Comment by Ravalli03** [comment]
Setting to false has also stopped the crashes for single player

**Comment by p455w0rd** [comment]
should be resolved since I removed shaders
